spring:
  datasource:
      url: jdbc:mysql://localhost:3306/tollplaza_pilot?serverTimezone=GMT&useLegacyDatetimeCode=false
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialization-node: always
  jpa: 
     database:-platform: org.hibernate.dialect.MySQLDialect
     hibernate: 
           ddl-auto: update 
      